// Barrel re-export — keeps routes.ts imports unchanged
export {
  getWidgetData,
  listTasks,
  getTask,
  createTask,
  updateTask,
  deleteTask,
  restoreTask,
  reorderTasks,
  searchTasks,
  getTaskCounts,
  listProjects,
  createProject,
  updateProject,
  deleteProject,
  seedSampleTasks,
  updateTaskVisibility,
  updateProjectVisibility,
  createTaskFromEmail,
} from './controllers/tasks-projects.controller';

export {
  listSubtasks,
  createSubtask,
  updateSubtask,
  deleteSubtask,
  reorderSubtasks,
  listActivities,
  listTemplates,
  createTemplate,
  updateTemplate,
  deleteTemplate,
  createTaskFromTemplate,
  listComments,
  createComment,
  deleteComment,
  listAttachments,
  uploadAttachment,
  deleteAttachment,
  downloadAttachment,
  listDependencies,
  addDependency,
  removeDependency,
  getBlockedTaskIds,
} from './controllers/extras.controller';
