// Barrel re-export — keeps routes.ts imports unchanged
export {
  listTasks,
  getTask,
  createTask,
  updateTask,
  deleteTask,
  restoreTask,
  searchTasks,
  reorderTasks,
  listProjects,
  getProject,
  createProject,
  updateProject,
  deleteProject,
  getTaskCounts,
  getWidgetData,
  updateTaskVisibility,
  updateProjectVisibility,
} from './services/tasks-projects.service';

export {
  listSubtasks,
  createSubtask,
  updateSubtask,
  deleteSubtask,
  reorderSubtasks,
  logActivity,
  listActivities,
  listTemplates,
  createTemplate,
  updateTemplate,
  deleteTemplate,
  createTaskFromTemplate,
  listComments,
  createComment,
  deleteComment,
  listAttachments,
  addAttachment,
  deleteAttachment,
  getAttachment,
  listDependencies,
  addDependency,
  removeDependency,
  getBlockedTaskIds,
} from './services/extras.service';
