// Barrel re-export — keeps routes.ts imports unchanged
export {
  getWidgetData,
  listItems,
  createFolder,
  uploadFiles,
  searchItems,
  listTrash,
  listFavourites,
  listRecent,
  listFolders,
  getStorageUsage,
  getItem,
  getBreadcrumbs,
  updateItem,
  deleteItem,
  restoreItem,
  permanentDelete,
  duplicateItem,
  copyItem,
  batchDelete,
  batchMove,
  batchFavourite,
  listItemsByType,
  seedSampleData,
  updateDriveItemVisibility,
} from './controllers/items.controller';

export {
  downloadZip,
  downloadFile,
  viewFile,
  previewFile,
  createLinkedDocument,
  createLinkedDrawing,
  createLinkedSpreadsheet,
} from './controllers/file-ops.controller';

export {
  listVersions,
  replaceFile,
  restoreVersion,
  downloadVersion,
  createShareLink,
  listShareLinks,
  deleteShareLink,
  shareWithUser,
  listShares,
  revokeShare,
  getSharedWithMe,
  getActivityLog,
  listComments,
  createComment,
  deleteComment,
} from './controllers/sharing.controller';
