import projectsRouter from './routes';
import type { ServerAppManifest } from '../../config/app-manifest.server';
import type { EntityObjectMeta } from '@atlasmail/shared';

const objects: EntityObjectMeta[] = [
  {
    id: 'clients',
    name: 'Clients',
    iconName: 'Building2',
    tableName: 'project_clients',
    description: 'Client organizations for project billing and management',
    standardFields: [
      { name: 'Name', slug: 'name', fieldType: 'text', isRequired: true },
      { name: 'Email', slug: 'email', fieldType: 'email', isRequired: false },
      { name: 'Phone', slug: 'phone', fieldType: 'phone', isRequired: false },
      { name: 'Address', slug: 'address', fieldType: 'text', isRequired: false },
      { name: 'City', slug: 'city', fieldType: 'text', isRequired: false },
      { name: 'State', slug: 'state', fieldType: 'text', isRequired: false },
      { name: 'Country', slug: 'country', fieldType: 'text', isRequired: false },
      { name: 'Postal code', slug: 'postal_code', fieldType: 'text', isRequired: false },
      { name: 'Currency', slug: 'currency', fieldType: 'text', isRequired: false },
      { name: 'Notes', slug: 'notes', fieldType: 'text', isRequired: false },
    ],
    relations: [
      { targetObjectId: 'projects:projects', type: 'one-to-many' },
      { targetObjectId: 'projects:invoices', type: 'one-to-many' },
    ],
  },
  {
    id: 'projects',
    name: 'Projects',
    iconName: 'FolderKanban',
    tableName: 'project_projects',
    description: 'Billable and non-billable projects with time tracking',
    standardFields: [
      { name: 'Name', slug: 'name', fieldType: 'text', isRequired: true },
      { name: 'Client', slug: 'client_id', fieldType: 'relation', isRequired: false },
      { name: 'Description', slug: 'description', fieldType: 'text', isRequired: false },
      { name: 'Billable', slug: 'billable', fieldType: 'boolean', isRequired: true },
      { name: 'Status', slug: 'status', fieldType: 'select', isRequired: true },
      { name: 'Estimated hours', slug: 'estimated_hours', fieldType: 'number', isRequired: false },
      { name: 'Estimated amount', slug: 'estimated_amount', fieldType: 'number', isRequired: false },
      { name: 'Start date', slug: 'start_date', fieldType: 'date', isRequired: false },
      { name: 'End date', slug: 'end_date', fieldType: 'date', isRequired: false },
      { name: 'Color', slug: 'color', fieldType: 'text', isRequired: false },
    ],
    relations: [
      { targetObjectId: 'projects:clients', type: 'many-to-one', foreignKey: 'client_id' },
      { targetObjectId: 'projects:time_entries', type: 'one-to-many' },
      { targetObjectId: 'projects:members', type: 'one-to-many' },
    ],
  },
  {
    id: 'members',
    name: 'Project members',
    iconName: 'Users',
    tableName: 'project_members',
    description: 'Team members assigned to projects with hourly rates',
    standardFields: [
      { name: 'User', slug: 'user_id', fieldType: 'relation', isRequired: true },
      { name: 'Project', slug: 'project_id', fieldType: 'relation', isRequired: true },
      { name: 'Hourly rate', slug: 'hourly_rate', fieldType: 'number', isRequired: false },
      { name: 'Role', slug: 'role', fieldType: 'select', isRequired: true },
    ],
    relations: [
      { targetObjectId: 'projects:projects', type: 'many-to-one', foreignKey: 'project_id' },
    ],
  },
  {
    id: 'time_entries',
    name: 'Time entries',
    iconName: 'Clock',
    tableName: 'project_time_entries',
    description: 'Tracked time entries for project work',
    standardFields: [
      { name: 'Project', slug: 'project_id', fieldType: 'relation', isRequired: true },
      { name: 'Duration (min)', slug: 'duration_minutes', fieldType: 'number', isRequired: true },
      { name: 'Work date', slug: 'work_date', fieldType: 'date', isRequired: true },
      { name: 'Start time', slug: 'start_time', fieldType: 'text', isRequired: false },
      { name: 'End time', slug: 'end_time', fieldType: 'text', isRequired: false },
      { name: 'Billable', slug: 'billable', fieldType: 'boolean', isRequired: true },
      { name: 'Billed', slug: 'billed', fieldType: 'boolean', isRequired: true },
      { name: 'Locked', slug: 'locked', fieldType: 'boolean', isRequired: true },
      { name: 'Notes', slug: 'notes', fieldType: 'text', isRequired: false },
      { name: 'Task description', slug: 'task_description', fieldType: 'text', isRequired: false },
    ],
    relations: [
      { targetObjectId: 'projects:projects', type: 'many-to-one', foreignKey: 'project_id' },
    ],
  },
  {
    id: 'invoices',
    name: 'Invoices',
    iconName: 'Receipt',
    tableName: 'project_invoices',
    description: 'Client invoices with line items and payment tracking',
    standardFields: [
      { name: 'Client', slug: 'client_id', fieldType: 'relation', isRequired: true },
      { name: 'Invoice number', slug: 'invoice_number', fieldType: 'text', isRequired: true },
      { name: 'Status', slug: 'status', fieldType: 'select', isRequired: true },
      { name: 'Amount', slug: 'amount', fieldType: 'number', isRequired: true },
      { name: 'Tax', slug: 'tax', fieldType: 'number', isRequired: false },
      { name: 'Currency', slug: 'currency', fieldType: 'text', isRequired: true },
      { name: 'Issue date', slug: 'issue_date', fieldType: 'date', isRequired: false },
      { name: 'Due date', slug: 'due_date', fieldType: 'date', isRequired: false },
      { name: 'Notes', slug: 'notes', fieldType: 'text', isRequired: false },
    ],
    relations: [
      { targetObjectId: 'projects:clients', type: 'many-to-one', foreignKey: 'client_id' },
      { targetObjectId: 'projects:invoice_line_items', type: 'one-to-many' },
    ],
  },
  {
    id: 'invoice_line_items',
    name: 'Invoice line items',
    iconName: 'List',
    tableName: 'project_invoice_line_items',
    description: 'Individual line items on an invoice',
    standardFields: [
      { name: 'Invoice', slug: 'invoice_id', fieldType: 'relation', isRequired: true },
      { name: 'Time entry', slug: 'time_entry_id', fieldType: 'relation', isRequired: false },
      { name: 'Description', slug: 'description', fieldType: 'text', isRequired: true },
      { name: 'Quantity', slug: 'quantity', fieldType: 'number', isRequired: true },
      { name: 'Unit price', slug: 'unit_price', fieldType: 'number', isRequired: true },
      { name: 'Amount', slug: 'amount', fieldType: 'number', isRequired: true },
    ],
    relations: [
      { targetObjectId: 'projects:invoices', type: 'many-to-one', foreignKey: 'invoice_id' },
      { targetObjectId: 'projects:time_entries', type: 'many-to-one', foreignKey: 'time_entry_id' },
    ],
  },
  {
    id: 'settings',
    name: 'Project settings',
    iconName: 'Settings',
    tableName: 'project_settings',
    description: 'Organization-level project and invoicing settings',
    standardFields: [
      { name: 'Invoice prefix', slug: 'invoice_prefix', fieldType: 'text', isRequired: true },
      { name: 'Default hourly rate', slug: 'default_hourly_rate', fieldType: 'number', isRequired: true },
      { name: 'Company name', slug: 'company_name', fieldType: 'text', isRequired: false },
      { name: 'Company address', slug: 'company_address', fieldType: 'text', isRequired: false },
      { name: 'Next invoice number', slug: 'next_invoice_number', fieldType: 'number', isRequired: true },
    ],
  },
];

export const projectsServerManifest: ServerAppManifest = {
  id: 'projects',
  name: 'Projects',
  labelKey: 'sidebar.projects',
  iconName: 'FolderKanban',
  color: '#0ea5e9',
  minPlan: 'starter',
  category: 'data',
  dependencies: [],
  defaultEnabled: true,
  version: '1.0.0',
  router: projectsRouter,
  routePrefix: '/projects',
  tables: [
    'project_clients',
    'project_projects',
    'project_members',
    'project_time_entries',
    'project_invoices',
    'project_invoice_line_items',
    'project_settings',
  ],
  objects,
};
